export const SUPPORTED_LANGUAGES = ["fr", "en", "es", "de"] as const;
export type Language = (typeof SUPPORTED_LANGUAGES)[number];
export type LanguagePreference = Language | "system";
export type TranslationParams = Record<string, string | number>;

export const LANGUAGE_NAMES: Record<LanguagePreference, string> = {
  system: "System / Système / Sistema",
  fr: "Français",
  en: "English",
  es: "Español",
  de: "Deutsch",
};

const fr = {
  "dialog.recovery": "Une sauvegarde de récupération a été trouvée. Voulez-vous la restaurer ?",
  "common.close": "Fermer", "common.cancel": "Annuler", "common.remove": "Retirer", "common.export": "Exporter", "common.import": "Importer", "common.copy": "Copier", "common.send": "Envoyer", "common.unknown": "inconnue",
  "menu.file": "Fichier", "menu.edit": "Édition", "menu.view": "Affichage", "menu.help": "Aide", "menu.new": "Nouveau", "menu.open": "Ouvrir…", "menu.save": "Enregistrer (Ctrl+S)", "menu.saveAs": "Enregistrer sous…", "menu.importImage": "Importer une image…", "menu.exportSvg": "Exporter en SVG…", "menu.exportPng": "Exporter en PNG…", "menu.undo": "Annuler (Ctrl+Z)", "menu.redo": "Rétablir (Ctrl+Y)", "menu.grid": "Basculer la grille", "menu.snap": "Magnétisme sur la grille", "menu.resetZoom": "Réinitialiser le zoom (100 %)", "menu.darkMode": "Mode sombre", "menu.settings": "Paramètres…", "menu.checkUpdates": "Vérifier les mises à jour…", "menu.welcome": "Fenêtre de bienvenue…", "menu.feedback": "Suggestion / Correction", "menu.about": "À propos d’Atelier Vecteur",
  "settings.title": "Paramètres", "settings.language": "Langue", "settings.languageHint": "La langue système est détectée automatiquement. Le changement est appliqué immédiatement.", "settings.theme": "Apparence", "settings.light": "Clair", "settings.dark": "Sombre", "settings.systemLanguage": "Système ({language})", "settings.welcomeTitle": "Démarrage",
  "welcome.eyebrow": "BIENVENUE", "welcome.title": "Merci d’utiliser Atelier Vecteur", "welcome.intro": "Atelier Vecteur est votre atelier de création vectorielle : dessinez, organisez et exportez vos illustrations SVG dans une application de bureau claire et rapide.", "welcome.thanks": "Merci de faire vivre ce logiciel indépendant par votre utilisation et vos retours.", "welcome.supportTitle": "Soutenir le projet", "welcome.supportText": "Si Atelier Vecteur vous est utile, un don aide à financer son développement, ses améliorations et sa maintenance.", "welcome.donate": "Faire un don avec PayPal", "welcome.later": "Plus tard", "welcome.showOnStartup": "Afficher cette fenêtre au démarrage", "welcome.notConfigured": "Le lien de don est momentanément indisponible.", "error.donationOpen": "Impossible d’ouvrir PayPal dans le navigateur.",
  "dialog.unsaved": "Les modifications non enregistrées seront perdues. Continuer ?", "error.openProject": "Impossible d’ouvrir ce fichier de projet.", "error.saveProject": "Impossible d’enregistrer le projet.", "error.exportSvg": "Impossible d’exporter le SVG.", "error.exportPng": "Impossible d’exporter le PNG.", "error.save": "Échec de l’enregistrement.", "error.updateSignature": "Cette mise à jour ne peut pas être installée automatiquement car la clé de sécurité a été renouvelée. Téléchargez et installez cette version manuellement une seule fois ; les mises à jour automatiques reprendront ensuite normalement.", "error.updateCheck": "Vérification des mises à jour impossible.", "error.updateServer": "Vérification impossible : serveur de mise à jour non configuré ou injoignable.", "error.fileVersion": "Version de fichier de projet invalide.", "error.fileFuture": "Ce projet a été créé avec une version plus récente d’Atelier Vecteur. Mettez l’application à jour pour l’ouvrir.", "error.fileInvalid": "Fichier de projet invalide ou corrompu.", "error.filePicker": "Impossible d’ouvrir le sélecteur de fichier.", "error.imageImport": "Échec de l’import de l’image.", "error.imageDimensions": "Impossible de lire les dimensions de l’image.", "error.traceEmpty": "Le tracé n’a produit aucune forme exploitable.", "error.textToPath": "Conversion en tracé impossible.", "error.imageUnsupported": "Format d’image non pris en charge (PNG, JPG, GIF et WebP uniquement).", "error.imageTooLarge": "Image trop volumineuse (limite : 30 Mo).", "error.imageEmpty": "Image vide.", "error.traceTooComplex": "Le tracé est trop complexe ({count} chemins, limite : {limit}).", "error.traceFailed": "Le tracé a échoué de façon inattendue.", "error.recoveryTooLarge": "La sauvegarde de récupération est trop volumineuse.", "error.destinationExtension": "Le fichier de destination doit avoir l’extension {extension}.", "error.invalidDimensions": "Les dimensions d’export doivent être supérieures à zéro.",
  "update.upToDate": "Vous utilisez déjà la dernière version.", "update.foundAutoInstalling": "Version {version} trouvée : téléchargement et installation automatiques en cours.", "update.downloadingToast": "Une mise à jour est en cours de téléchargement et sera installée automatiquement.",
  "about.title": "À propos d’Atelier Vecteur", "about.version": "Version {version}", "about.description": "Éditeur vectoriel de bureau pour créer, modifier et exporter des illustrations SVG. Il réunit formes, plume, texte, édition de nœuds, calques, plans de travail, dégradés, motifs, filtres et vectorisation d’images dans une interface multilingue.", "about.credits": "Crédits", "about.design": "Conception et développement : bob59", "about.builtWith": "Construit avec Tauri, Rust, React et TypeScript.", "about.engines": "Vectorisation et rendu assurés notamment par vtracer et resvg.", "about.footer": "Créé par bob59 · © 2026",
  "feedback.title": "Suggestion / Correction", "feedback.subtitle": "Proposez une amélioration ou décrivez un problème.", "feedback.subject": "Sujet", "feedback.message": "Message", "feedback.placeholder": "Expliquez votre suggestion ou les étapes du problème…", "feedback.defaultSubject": "Atelier Vecteur - Suggestion / Correction", "feedback.application": "Application : Atelier Vecteur", "feedback.to": "À", "feedback.copied": "Adresse et message copiés.",
  "status.modified": "● Modifié", "status.untitled": "sans titre", "status.saved": "✓ Enregistré", "status.selected": "{count} sélectionné(s)", "status.snapOn": "Aimant activé", "status.snapOff": "Aimant désactivé",
  "tool.select": "Sélection", "tool.rect": "Rectangle", "tool.ellipse": "Ellipse", "tool.line": "Ligne", "tool.polygon": "Polygone", "tool.pen": "Plume", "tool.text": "Texte",
  "panel.properties": "Propriétés", "panel.selectHint": "Sélectionnez une forme pour modifier ses propriétés.", "panel.transform": "Position et transformation", "panel.rotation": "Rotation", "panel.scaleX": "Échelle X", "panel.scaleY": "Échelle Y", "panel.keepRatio": "Conserver les proportions", "panel.fill": "Remplissage", "panel.enableFill": "Activer le remplissage", "panel.stroke": "Contour", "panel.enableStroke": "Activer le contour", "panel.opacity": "Opacité", "panel.solid": "Continu", "panel.dashed": "Tirets", "panel.dotted": "Pointillés", "panel.font": "Police", "panel.lightWeight": "Léger", "panel.normalWeight": "Normal", "panel.boldWeight": "Gras", "panel.left": "Gauche", "panel.center": "Centre", "panel.right": "Droite", "panel.convertPath": "Convertir en tracé", "panel.converting": "Conversion…",
  "align.title": "Alignement", "align.left": "Aligner à gauche", "align.centerH": "Centrer horizontalement", "align.right": "Aligner à droite", "align.top": "Aligner en haut", "align.centerV": "Centrer verticalement", "align.bottom": "Aligner en bas", "align.distributeH": "Distribuer horizontalement", "align.distributeV": "Distribuer verticalement",
  "boolean.title": "Opérations booléennes", "boolean.union": "Union", "boolean.subtract": "Soustraction", "boolean.intersect": "Intersection", "boolean.exclude": "Exclusion",
  "artboard.title": "Plans de travail", "artboard.defaultName": "Plan de travail {number}", "artboard.add": "Ajouter un plan de travail", "artboard.delete": "Supprimer le plan de travail", "layer.title": "Calques", "layer.defaultName": "Calque {number}", "layer.add": "Ajouter un calque", "layer.rename": "Renommer le calque", "layer.reorder": "Réordonner les calques", "layer.delete": "Supprimer le calque", "layer.hide": "Masquer", "layer.show": "Afficher", "layer.unlock": "Déverrouiller", "layer.lock": "Verrouiller", "layer.up": "Monter", "layer.down": "Descendre",
  "gradient.title": "Dégradé", "gradient.apply": "Appliquer un dégradé au remplissage", "gradient.linear": "Linéaire", "gradient.radial": "Radial", "gradient.stop": "+ Point d’arrêt", "pattern.title": "Motif", "pattern.dots": "Points", "pattern.stripes": "Rayures", "pattern.grid": "Grille", "pattern.checkerboard": "Damier", "pattern.size": "Taille", "pattern.colors": "Couleur / Fond", "filter.title": "Filtre", "filter.blur": "Flou", "filter.shadow": "Ombre portée", "filter.radius": "Rayon", "filter.offset": "Décalage X / Y", "filter.colorOpacity": "Couleur / Opacité",
  "png.title": "Exporter en PNG", "png.width": "Largeur (px)", "png.height": "Hauteur (px)", "image.title": "Importer une image", "image.choose": "Choisir un fichier…", "image.raster": "Image intégrée", "image.vector": "Vectoriel (tracé)", "image.rasterHint": "L’image est intégrée telle quelle dans le SVG (encodée en base64).", "image.quickSettings": "Réglages rapides", "image.presetLogo": "Logo couleur", "image.presetSilhouette": "Silhouette", "image.presetDetailed": "Dessin détaillé", "image.presetStencil": "Découpe / pochoir", "image.colorMode": "Mode couleur", "image.color": "Couleur", "image.blackWhite": "Noir et blanc", "image.traceStyle": "Style de tracé", "image.curves": "Courbes", "image.polygons": "Polygones", "image.pixels": "Pixels (brut)", "image.layers": "Calques", "image.stacked": "Empilés", "image.cutout": "Découpés", "image.colorPrecision": "Précision des couleurs", "image.noise": "Filtrer le bruit (px)", "image.corner": "Seuil des angles", "image.advanced": "Options avancées", "image.layerDifference": "Différence entre calques", "image.length": "Seuil de longueur", "image.iterations": "Itérations max", "image.splice": "Seuil de jonction", "image.pathPrecision": "Précision du tracé (décimales)", "image.importing": "Import…",
  "command.addArtboard": "Ajouter un plan de travail", "command.deleteArtboard": "Supprimer le plan de travail", "command.editArtboard": "Modifier le plan de travail", "command.addLayer": "Ajouter un calque", "command.applyBlur": "Appliquer un flou", "command.applyShadow": "Appliquer une ombre portée", "command.removeFilter": "Retirer le filtre", "command.applyGradient": "Appliquer un dégradé", "command.removeGradient": "Retirer le dégradé", "command.applyPattern": "Appliquer un motif", "command.removePattern": "Retirer le motif", "command.changeFont": "Modifier la police", "command.changeText": "Modifier le texte", "command.importImage": "Importer une image", "command.traceImage": "Tracer l’image", "command.addElement": "Ajouter un élément", "command.addElements": "Ajouter des éléments", "command.delete": "Supprimer", "command.group": "Grouper", "command.ungroup": "Dégrouper", "command.transform": "Transformer", "command.resize": "Redimensionner", "command.style": "Modifier le style", "command.path": "Modifier le tracé", "command.gradient": "Modifier le dégradé", "command.pattern": "Modifier le motif", "command.filter": "Modifier le filtre", "command.textToPath": "Convertir le texte en tracé", "command.booleanUnion": "Union de tracés", "command.booleanSubtract": "Soustraction de tracés", "command.booleanIntersect": "Intersection de tracés", "command.booleanExclude": "Exclusion de tracés",
  "document.defaultText": "Texte", "file.project": "Projet Atelier Vecteur", "file.image": "Image", "file.untitled": "sans-titre",
} as const;

export type MessageKey = keyof typeof fr;

const en: Record<MessageKey, string> = Object.fromEntries(Object.keys(fr).map((key) => [key, key])) as Record<MessageKey, string>;
const es: Record<MessageKey, string> = { ...en };
const de: Record<MessageKey, string> = { ...en };

// Complete English catalogue; Spanish and German are overlaid below and always fall back to English.
Object.assign(en, {
  "dialog.recovery":"A recovery backup was found. Do you want to restore it?",
  "common.close":"Close","common.cancel":"Cancel","common.remove":"Remove","common.export":"Export","common.import":"Import","common.copy":"Copy","common.send":"Send","common.unknown":"unknown",
  "menu.file":"File","menu.edit":"Edit","menu.view":"View","menu.help":"Help","menu.new":"New","menu.open":"Open…","menu.save":"Save (Ctrl+S)","menu.saveAs":"Save as…","menu.importImage":"Import image…","menu.exportSvg":"Export as SVG…","menu.exportPng":"Export as PNG…","menu.undo":"Undo (Ctrl+Z)","menu.redo":"Redo (Ctrl+Y)","menu.grid":"Toggle grid","menu.snap":"Snap to grid","menu.resetZoom":"Reset zoom (100%)","menu.darkMode":"Dark mode","menu.settings":"Settings…","menu.checkUpdates":"Check for updates…","menu.welcome":"Welcome window…","menu.feedback":"Suggestion / Bug report","menu.about":"About Atelier Vecteur",
  "settings.title":"Settings","settings.language":"Language","settings.languageHint":"The system language is detected automatically. Changes apply immediately.","settings.theme":"Appearance","settings.light":"Light","settings.dark":"Dark","settings.systemLanguage":"System ({language})","settings.welcomeTitle":"Startup",
  "welcome.eyebrow":"WELCOME","welcome.title":"Thank you for using Atelier Vecteur","welcome.intro":"Atelier Vecteur is your vector creation workshop: draw, organize and export SVG illustrations in a clear and fast desktop application.","welcome.thanks":"Thank you for helping this independent software thrive through your use and feedback.","welcome.supportTitle":"Support the project","welcome.supportText":"If Atelier Vecteur is useful to you, a donation helps fund its development, improvements and maintenance.","welcome.donate":"Donate with PayPal","welcome.later":"Later","welcome.showOnStartup":"Show this window at startup","welcome.notConfigured":"The donation link is temporarily unavailable.","error.donationOpen":"PayPal could not be opened in the browser.",
  "dialog.unsaved":"Unsaved changes will be lost. Continue?","error.openProject":"Could not open this project file.","error.saveProject":"Could not save the project.","error.exportSvg":"Could not export the SVG.","error.exportPng":"Could not export the PNG.","error.save":"Save failed.","error.updateSignature":"This update can't be installed automatically because the security key was renewed. Download and install this version manually once; automatic updates will then resume normally.","error.updateCheck":"Could not check for updates.","error.updateServer":"Could not check for updates: the update server is unavailable or not configured.","error.fileVersion":"Invalid project file version.","error.fileFuture":"This project was created with a newer version of Atelier Vecteur. Update the application to open it.","error.fileInvalid":"Invalid or corrupted project file.","error.filePicker":"Could not open the file picker.","error.imageImport":"Image import failed.","error.imageDimensions":"Could not read the image dimensions.","error.traceEmpty":"Tracing produced no usable shape.","error.textToPath":"Could not convert text to path.","error.imageUnsupported":"Unsupported image format (PNG, JPG, GIF and WebP only).","error.imageTooLarge":"Image is too large (30 MB limit).","error.imageEmpty":"Empty image.","error.traceTooComplex":"The trace is too complex ({count} paths, limit: {limit}).","error.traceFailed":"Tracing failed unexpectedly.","error.recoveryTooLarge":"The recovery file is too large.","error.destinationExtension":"The destination file must use the {extension} extension.","error.invalidDimensions":"Export dimensions must be greater than zero.",
  "update.upToDate":"You already have the latest version.","update.foundAutoInstalling":"Version {version} found: downloading and installing automatically.","update.downloadingToast":"An update is downloading and will be installed automatically.",
  "about.title":"About Atelier Vecteur","about.version":"Version {version}","about.description":"Desktop vector editor for creating, editing and exporting SVG illustrations. It combines shapes, pen, text, node editing, layers, artboards, gradients, patterns, filters and image tracing in a multilingual interface.","about.credits":"Credits","about.design":"Design and development: bob59","about.builtWith":"Built with Tauri, Rust, React and TypeScript.","about.engines":"Tracing and rendering powered in particular by vtracer and resvg.","about.footer":"Created by bob59 · © 2026",
  "feedback.title":"Suggestion / Bug report","feedback.subtitle":"Suggest an improvement or describe a problem.","feedback.subject":"Subject","feedback.message":"Message","feedback.placeholder":"Describe your suggestion or the steps that caused the problem…","feedback.defaultSubject":"Atelier Vecteur - Suggestion / Bug report","feedback.application":"Application: Atelier Vecteur","feedback.to":"To","feedback.copied":"Address and message copied.",
  "status.modified":"● Modified","status.untitled":"untitled","status.saved":"✓ Saved","status.selected":"{count} selected","status.snapOn":"Snap enabled","status.snapOff":"Snap disabled",
  "tool.select":"Select","tool.rect":"Rectangle","tool.ellipse":"Ellipse","tool.line":"Line","tool.polygon":"Polygon","tool.pen":"Pen","tool.text":"Text",
  "panel.properties":"Properties","panel.selectHint":"Select a shape to edit its properties.","panel.transform":"Position and transform","panel.rotation":"Rotation","panel.scaleX":"Scale X","panel.scaleY":"Scale Y","panel.keepRatio":"Keep proportions","panel.fill":"Fill","panel.enableFill":"Enable fill","panel.stroke":"Stroke","panel.enableStroke":"Enable stroke","panel.opacity":"Opacity","panel.solid":"Solid","panel.dashed":"Dashed","panel.dotted":"Dotted","panel.font":"Font","panel.lightWeight":"Light","panel.normalWeight":"Normal","panel.boldWeight":"Bold","panel.left":"Left","panel.center":"Center","panel.right":"Right","panel.convertPath":"Convert to path","panel.converting":"Converting…",
  "align.title":"Alignment","align.left":"Align left","align.centerH":"Center horizontally","align.right":"Align right","align.top":"Align top","align.centerV":"Center vertically","align.bottom":"Align bottom","align.distributeH":"Distribute horizontally","align.distributeV":"Distribute vertically",
  "boolean.title":"Boolean operations","boolean.union":"Union","boolean.subtract":"Subtract","boolean.intersect":"Intersect","boolean.exclude":"Exclude",
  "artboard.title":"Artboards","artboard.defaultName":"Artboard {number}","artboard.add":"Add artboard","artboard.delete":"Delete artboard","layer.title":"Layers","layer.defaultName":"Layer {number}","layer.add":"Add layer","layer.rename":"Rename layer","layer.reorder":"Reorder layers","layer.delete":"Delete layer","layer.hide":"Hide","layer.show":"Show","layer.unlock":"Unlock","layer.lock":"Lock","layer.up":"Move up","layer.down":"Move down",
  "gradient.title":"Gradient","gradient.apply":"Apply a gradient to fill","gradient.linear":"Linear","gradient.radial":"Radial","gradient.stop":"+ Stop","pattern.title":"Pattern","pattern.dots":"Dots","pattern.stripes":"Stripes","pattern.grid":"Grid","pattern.checkerboard":"Checkerboard","pattern.size":"Size","pattern.colors":"Color / Background","filter.title":"Filter","filter.blur":"Blur","filter.shadow":"Drop shadow","filter.radius":"Radius","filter.offset":"X / Y offset","filter.colorOpacity":"Color / Opacity",
  "png.title":"Export as PNG","png.width":"Width (px)","png.height":"Height (px)","image.title":"Import image","image.choose":"Choose a file…","image.raster":"Embedded image","image.vector":"Vector (trace)","image.rasterHint":"The image is embedded as-is in the SVG (base64 encoded).","image.quickSettings":"Quick settings","image.presetLogo":"Color logo","image.presetSilhouette":"Silhouette","image.presetDetailed":"Detailed drawing","image.presetStencil":"Cutout / stencil","image.colorMode":"Color mode","image.color":"Color","image.blackWhite":"Black and white","image.traceStyle":"Trace style","image.curves":"Curves","image.polygons":"Polygons","image.pixels":"Pixels (raw)","image.layers":"Layers","image.stacked":"Stacked","image.cutout":"Cut out","image.colorPrecision":"Color precision","image.noise":"Filter noise (px)","image.corner":"Corner threshold","image.advanced":"Advanced options","image.layerDifference":"Layer difference","image.length":"Length threshold","image.iterations":"Max iterations","image.splice":"Splice threshold","image.pathPrecision":"Path precision (decimals)","image.importing":"Importing…",
  "command.addArtboard":"Add artboard","command.deleteArtboard":"Delete artboard","command.editArtboard":"Edit artboard","command.addLayer":"Add layer","command.applyBlur":"Apply blur","command.applyShadow":"Apply drop shadow","command.removeFilter":"Remove filter","command.applyGradient":"Apply gradient","command.removeGradient":"Remove gradient","command.applyPattern":"Apply pattern","command.removePattern":"Remove pattern","command.changeFont":"Change font","command.changeText":"Edit text","command.importImage":"Import image","command.traceImage":"Trace image","command.addElement":"Add element","command.addElements":"Add elements","command.delete":"Delete","command.group":"Group","command.ungroup":"Ungroup","command.transform":"Transform","command.resize":"Resize","command.style":"Change style","command.path":"Edit path","command.gradient":"Edit gradient","command.pattern":"Edit pattern","command.filter":"Edit filter","command.textToPath":"Convert text to path","command.booleanUnion":"Union paths","command.booleanSubtract":"Subtract paths","command.booleanIntersect":"Intersect paths","command.booleanExclude":"Exclude paths",
  "document.defaultText":"Text","file.project":"Atelier Vecteur project","file.image":"Image","file.untitled":"untitled"
});

Object.assign(es, en, {
  "dialog.recovery":"Se encontró una copia de recuperación. ¿Quieres restaurarla?",
  "common.close":"Cerrar","common.cancel":"Cancelar","common.remove":"Quitar","common.export":"Exportar","common.import":"Importar","common.copy":"Copiar","common.send":"Enviar","common.unknown":"desconocida",
  "menu.file":"Archivo","menu.edit":"Edición","menu.view":"Ver","menu.help":"Ayuda","menu.new":"Nuevo","menu.open":"Abrir…","menu.save":"Guardar (Ctrl+S)","menu.saveAs":"Guardar como…","menu.importImage":"Importar imagen…","menu.exportSvg":"Exportar como SVG…","menu.exportPng":"Exportar como PNG…","menu.undo":"Deshacer (Ctrl+Z)","menu.redo":"Rehacer (Ctrl+Y)","menu.grid":"Mostrar/ocultar cuadrícula","menu.snap":"Ajustar a la cuadrícula","menu.resetZoom":"Restablecer zoom (100 %)","menu.darkMode":"Modo oscuro","menu.settings":"Configuración…","menu.checkUpdates":"Buscar actualizaciones…","menu.welcome":"Ventana de bienvenida…","menu.feedback":"Sugerencia / Corrección","menu.about":"Acerca de Atelier Vecteur",
  "settings.title":"Configuración","settings.language":"Idioma","settings.languageHint":"El idioma del sistema se detecta automáticamente. El cambio se aplica de inmediato.","settings.theme":"Apariencia","settings.light":"Claro","settings.dark":"Oscuro","settings.systemLanguage":"Sistema ({language})","settings.welcomeTitle":"Inicio",
  "welcome.eyebrow":"BIENVENIDO","welcome.title":"Gracias por usar Atelier Vecteur","welcome.intro":"Atelier Vecteur es tu taller de creación vectorial: dibuja, organiza y exporta ilustraciones SVG en una aplicación de escritorio clara y rápida.","welcome.thanks":"Gracias por ayudar a que este software independiente siga creciendo con tu uso y comentarios.","welcome.supportTitle":"Apoyar el proyecto","welcome.supportText":"Si Atelier Vecteur te resulta útil, una donación ayuda a financiar su desarrollo, mejoras y mantenimiento.","welcome.donate":"Donar con PayPal","welcome.later":"Más tarde","welcome.showOnStartup":"Mostrar esta ventana al iniciar","welcome.notConfigured":"El enlace de donación no está disponible temporalmente.","error.donationOpen":"No se pudo abrir PayPal en el navegador.",
  "dialog.unsaved":"Se perderán los cambios no guardados. ¿Continuar?","error.openProject":"No se pudo abrir el proyecto.","error.saveProject":"No se pudo guardar el proyecto.","error.exportSvg":"No se pudo exportar el SVG.","error.exportPng":"No se pudo exportar el PNG.","error.save":"Error al guardar.","error.updateSignature":"Esta actualización no se puede instalar automáticamente porque la clave de seguridad se ha renovado. Descarga e instala esta versión manualmente una sola vez; las actualizaciones automáticas se reanudarán con normalidad.","error.updateCheck":"No se pudieron buscar actualizaciones.","error.updateServer":"El servidor de actualizaciones no está disponible o configurado.","error.fileVersion":"Versión de proyecto no válida.","error.fileFuture":"Este proyecto fue creado con una versión más reciente de Atelier Vecteur. Actualiza la aplicación para abrirlo.","error.fileInvalid":"Proyecto no válido o dañado.","error.filePicker":"No se pudo abrir el selector de archivos.","error.imageImport":"Error al importar la imagen.","error.imageDimensions":"No se pudieron leer las dimensiones de la imagen.","error.traceEmpty":"El trazado no produjo ninguna forma utilizable.","error.textToPath":"No se pudo convertir el texto en trazado.","error.imageUnsupported":"Formato de imagen no compatible (solo PNG, JPG, GIF y WebP).","error.imageTooLarge":"La imagen es demasiado grande (límite: 30 MB).","error.imageEmpty":"Imagen vacía.","error.traceTooComplex":"El trazado es demasiado complejo ({count} rutas, límite: {limit}).","error.traceFailed":"El trazado falló inesperadamente.","error.recoveryTooLarge":"El archivo de recuperación es demasiado grande.","error.destinationExtension":"El archivo de destino debe tener la extensión {extension}.","error.invalidDimensions":"Las dimensiones de exportación deben ser mayores que cero.",
  "update.upToDate":"Ya tienes la última versión.","update.foundAutoInstalling":"Versión {version} encontrada: descarga e instalación automáticas en curso.","update.downloadingToast":"Se está descargando una actualización que se instalará automáticamente.",
  "about.title":"Acerca de Atelier Vecteur","about.version":"Versión {version}","about.description":"Editor vectorial de escritorio para crear, modificar y exportar ilustraciones SVG, con formas, pluma, texto, nodos, capas, mesas de trabajo, degradados, patrones, filtros y vectorización de imágenes.","about.credits":"Créditos","about.design":"Diseño y desarrollo: bob59","about.builtWith":"Creado con Tauri, Rust, React y TypeScript.","about.engines":"Vectorización y renderizado mediante vtracer y resvg.","about.footer":"Creado por bob59 · © 2026",
  "feedback.title":"Sugerencia / Corrección","feedback.subtitle":"Propón una mejora o describe un problema.","feedback.subject":"Asunto","feedback.message":"Mensaje","feedback.placeholder":"Explica tu sugerencia o los pasos que causaron el problema…","feedback.defaultSubject":"Atelier Vecteur - Sugerencia / Corrección","feedback.application":"Aplicación: Atelier Vecteur","feedback.to":"Para","feedback.copied":"Dirección y mensaje copiados.",
  "status.modified":"● Modificado","status.untitled":"sin título","status.saved":"✓ Guardado","status.selected":"{count} seleccionado(s)","status.snapOn":"Ajuste activado","status.snapOff":"Ajuste desactivado",
  "tool.select":"Selección","tool.rect":"Rectángulo","tool.ellipse":"Elipse","tool.line":"Línea","tool.polygon":"Polígono","tool.pen":"Pluma","tool.text":"Texto",
  "panel.properties":"Propiedades","panel.selectHint":"Selecciona una forma para modificar sus propiedades.","panel.transform":"Posición y transformación","panel.rotation":"Rotación","panel.scaleX":"Escala X","panel.scaleY":"Escala Y","panel.keepRatio":"Mantener proporciones","panel.fill":"Relleno","panel.enableFill":"Activar relleno","panel.stroke":"Contorno","panel.enableStroke":"Activar contorno","panel.opacity":"Opacidad","panel.solid":"Continuo","panel.dashed":"Guiones","panel.dotted":"Punteado","panel.font":"Fuente","panel.lightWeight":"Ligera","panel.normalWeight":"Normal","panel.boldWeight":"Negrita","panel.left":"Izquierda","panel.center":"Centro","panel.right":"Derecha","panel.convertPath":"Convertir en trazado","panel.converting":"Convirtiendo…",
  "align.title":"Alineación","align.left":"Alinear a la izquierda","align.centerH":"Centrar horizontalmente","align.right":"Alinear a la derecha","align.top":"Alinear arriba","align.centerV":"Centrar verticalmente","align.bottom":"Alinear abajo","align.distributeH":"Distribuir horizontalmente","align.distributeV":"Distribuir verticalmente",
  "boolean.title":"Operaciones booleanas","boolean.union":"Unión","boolean.subtract":"Resta","boolean.intersect":"Intersección","boolean.exclude":"Exclusión",
  "artboard.title":"Mesas de trabajo","artboard.defaultName":"Mesa de trabajo {number}","artboard.add":"Añadir mesa de trabajo","artboard.delete":"Eliminar mesa de trabajo","layer.title":"Capas","layer.defaultName":"Capa {number}","layer.add":"Añadir capa","layer.rename":"Renombrar capa","layer.reorder":"Reordenar capas","layer.delete":"Eliminar capa","layer.hide":"Ocultar","layer.show":"Mostrar","layer.unlock":"Desbloquear","layer.lock":"Bloquear","layer.up":"Subir","layer.down":"Bajar",
  "gradient.title":"Degradado","gradient.apply":"Aplicar degradado al relleno","gradient.linear":"Lineal","gradient.radial":"Radial","gradient.stop":"+ Parada","pattern.title":"Patrón","pattern.dots":"Puntos","pattern.stripes":"Rayas","pattern.grid":"Cuadrícula","pattern.checkerboard":"Damero","pattern.size":"Tamaño","pattern.colors":"Color / Fondo","filter.title":"Filtro","filter.blur":"Desenfoque","filter.shadow":"Sombra paralela","filter.radius":"Radio","filter.offset":"Desplazamiento X / Y","filter.colorOpacity":"Color / Opacidad",
  "png.title":"Exportar como PNG","png.width":"Anchura (px)","png.height":"Altura (px)","image.title":"Importar imagen","image.choose":"Elegir archivo…","image.raster":"Imagen integrada","image.vector":"Vectorial (trazado)","image.rasterHint":"La imagen se integra tal cual en el SVG (codificada en base64).","image.quickSettings":"Ajustes rápidos","image.presetLogo":"Logo en color","image.presetSilhouette":"Silueta","image.presetDetailed":"Dibujo detallado","image.presetStencil":"Recorte / plantilla","image.colorMode":"Modo de color","image.color":"Color","image.blackWhite":"Blanco y negro","image.traceStyle":"Estilo de trazado","image.curves":"Curvas","image.polygons":"Polígonos","image.pixels":"Píxeles (bruto)","image.layers":"Capas","image.stacked":"Apiladas","image.cutout":"Recortadas","image.colorPrecision":"Precisión del color","image.noise":"Filtrar ruido (px)","image.corner":"Umbral de ángulos","image.advanced":"Opciones avanzadas","image.layerDifference":"Diferencia entre capas","image.length":"Umbral de longitud","image.iterations":"Iteraciones máximas","image.splice":"Umbral de unión","image.pathPrecision":"Precisión del trazado (decimales)","image.importing":"Importando…",
  "document.defaultText":"Texto","file.project":"Proyecto de Atelier Vecteur","file.image":"Imagen","file.untitled":"sin-título"
});

Object.assign(de, en, {
  "dialog.recovery":"Eine Wiederherstellungssicherung wurde gefunden. Soll sie wiederhergestellt werden?",
  "common.close":"Schließen","common.cancel":"Abbrechen","common.remove":"Entfernen","common.export":"Exportieren","common.import":"Importieren","common.copy":"Kopieren","common.send":"Senden","common.unknown":"unbekannt",
  "menu.file":"Datei","menu.edit":"Bearbeiten","menu.view":"Ansicht","menu.help":"Hilfe","menu.new":"Neu","menu.open":"Öffnen…","menu.save":"Speichern (Strg+S)","menu.saveAs":"Speichern unter…","menu.importImage":"Bild importieren…","menu.exportSvg":"Als SVG exportieren…","menu.exportPng":"Als PNG exportieren…","menu.undo":"Rückgängig (Strg+Z)","menu.redo":"Wiederholen (Strg+Y)","menu.grid":"Raster ein-/ausblenden","menu.snap":"Am Raster ausrichten","menu.resetZoom":"Zoom zurücksetzen (100 %)","menu.darkMode":"Dunkler Modus","menu.settings":"Einstellungen…","menu.checkUpdates":"Nach Updates suchen…","menu.welcome":"Willkommensfenster…","menu.feedback":"Vorschlag / Fehler melden","menu.about":"Über Atelier Vecteur",
  "settings.title":"Einstellungen","settings.language":"Sprache","settings.languageHint":"Die Systemsprache wird automatisch erkannt. Änderungen werden sofort angewendet.","settings.theme":"Darstellung","settings.light":"Hell","settings.dark":"Dunkel","settings.systemLanguage":"System ({language})","settings.welcomeTitle":"Start",
  "welcome.eyebrow":"WILLKOMMEN","welcome.title":"Danke, dass du Atelier Vecteur verwendest","welcome.intro":"Atelier Vecteur ist deine Werkstatt für Vektorgrafiken: Zeichne, organisiere und exportiere SVG-Illustrationen in einer übersichtlichen und schnellen Desktop-Anwendung.","welcome.thanks":"Danke, dass du diese unabhängige Software durch deine Nutzung und dein Feedback unterstützt.","welcome.supportTitle":"Projekt unterstützen","welcome.supportText":"Wenn Atelier Vecteur für dich nützlich ist, hilft eine Spende bei Entwicklung, Verbesserungen und Wartung.","welcome.donate":"Mit PayPal spenden","welcome.later":"Später","welcome.showOnStartup":"Dieses Fenster beim Start anzeigen","welcome.notConfigured":"Der Spendenlink ist vorübergehend nicht verfügbar.","error.donationOpen":"PayPal konnte nicht im Browser geöffnet werden.",
  "dialog.unsaved":"Nicht gespeicherte Änderungen gehen verloren. Fortfahren?","error.openProject":"Die Projektdatei konnte nicht geöffnet werden.","error.saveProject":"Das Projekt konnte nicht gespeichert werden.","error.exportSvg":"SVG konnte nicht exportiert werden.","error.exportPng":"PNG konnte nicht exportiert werden.","error.save":"Speichern fehlgeschlagen.","error.updateSignature":"Dieses Update kann nicht automatisch installiert werden, da der Sicherheitsschlüssel erneuert wurde. Lade diese Version einmal manuell herunter und installiere sie; automatische Updates funktionieren danach wieder normal.","error.updateCheck":"Updates konnten nicht geprüft werden.","error.updateServer":"Der Update-Server ist nicht verfügbar oder nicht konfiguriert.","error.fileVersion":"Ungültige Projektdateiversion.","error.fileFuture":"Dieses Projekt wurde mit einer neueren Version von Atelier Vecteur erstellt. Aktualisiere die Anwendung, um es zu öffnen.","error.fileInvalid":"Ungültige oder beschädigte Projektdatei.","error.filePicker":"Die Dateiauswahl konnte nicht geöffnet werden.","error.imageImport":"Bildimport fehlgeschlagen.","error.imageDimensions":"Die Bildabmessungen konnten nicht gelesen werden.","error.traceEmpty":"Die Vektorisierung hat keine verwendbare Form erzeugt.","error.textToPath":"Text konnte nicht in einen Pfad umgewandelt werden.","error.imageUnsupported":"Nicht unterstütztes Bildformat (nur PNG, JPG, GIF und WebP).","error.imageTooLarge":"Das Bild ist zu groß (maximal 30 MB).","error.imageEmpty":"Leeres Bild.","error.traceTooComplex":"Die Vektorisierung ist zu komplex ({count} Pfade, Limit: {limit}).","error.traceFailed":"Die Vektorisierung ist unerwartet fehlgeschlagen.","error.recoveryTooLarge":"Die Wiederherstellungsdatei ist zu groß.","error.destinationExtension":"Die Zieldatei muss die Erweiterung {extension} haben.","error.invalidDimensions":"Die Exportabmessungen müssen größer als null sein.",
  "update.upToDate":"Du verwendest bereits die neueste Version.","update.foundAutoInstalling":"Version {version} gefunden: automatischer Download und Installation laufen.","update.downloadingToast":"Ein Update wird heruntergeladen und automatisch installiert.",
  "about.title":"Über Atelier Vecteur","about.version":"Version {version}","about.description":"Desktop-Vektoreditor zum Erstellen, Bearbeiten und Exportieren von SVG-Illustrationen mit Formen, Zeichenstift, Text, Knoten, Ebenen, Zeichenflächen, Verläufen, Mustern, Filtern und Bildvektorisierung.","about.credits":"Mitwirkende","about.design":"Design und Entwicklung: bob59","about.builtWith":"Erstellt mit Tauri, Rust, React und TypeScript.","about.engines":"Vektorisierung und Rendering unter anderem mit vtracer und resvg.","about.footer":"Erstellt von bob59 · © 2026",
  "feedback.title":"Vorschlag / Fehler melden","feedback.subtitle":"Schlage eine Verbesserung vor oder beschreibe ein Problem.","feedback.subject":"Betreff","feedback.message":"Nachricht","feedback.placeholder":"Beschreibe deinen Vorschlag oder die Schritte zum Problem…","feedback.defaultSubject":"Atelier Vecteur - Vorschlag / Fehler","feedback.application":"Anwendung: Atelier Vecteur","feedback.to":"An","feedback.copied":"Adresse und Nachricht kopiert.",
  "status.modified":"● Geändert","status.untitled":"unbenannt","status.saved":"✓ Gespeichert","status.selected":"{count} ausgewählt","status.snapOn":"Einrasten aktiviert","status.snapOff":"Einrasten deaktiviert",
  "tool.select":"Auswahl","tool.rect":"Rechteck","tool.ellipse":"Ellipse","tool.line":"Linie","tool.polygon":"Polygon","tool.pen":"Zeichenstift","tool.text":"Text",
  "panel.properties":"Eigenschaften","panel.selectHint":"Wähle eine Form aus, um ihre Eigenschaften zu bearbeiten.","panel.transform":"Position und Transformation","panel.rotation":"Drehung","panel.scaleX":"Skalierung X","panel.scaleY":"Skalierung Y","panel.keepRatio":"Proportionen beibehalten","panel.fill":"Füllung","panel.enableFill":"Füllung aktivieren","panel.stroke":"Kontur","panel.enableStroke":"Kontur aktivieren","panel.opacity":"Deckkraft","panel.solid":"Durchgehend","panel.dashed":"Gestrichelt","panel.dotted":"Gepunktet","panel.font":"Schrift","panel.lightWeight":"Leicht","panel.normalWeight":"Normal","panel.boldWeight":"Fett","panel.left":"Links","panel.center":"Mitte","panel.right":"Rechts","panel.convertPath":"In Pfad umwandeln","panel.converting":"Wird umgewandelt…",
  "align.title":"Ausrichtung","align.left":"Links ausrichten","align.centerH":"Horizontal zentrieren","align.right":"Rechts ausrichten","align.top":"Oben ausrichten","align.centerV":"Vertikal zentrieren","align.bottom":"Unten ausrichten","align.distributeH":"Horizontal verteilen","align.distributeV":"Vertikal verteilen",
  "boolean.title":"Boolesche Operationen","boolean.union":"Vereinigung","boolean.subtract":"Subtraktion","boolean.intersect":"Schnittmenge","boolean.exclude":"Ausschluss",
  "artboard.title":"Zeichenflächen","artboard.defaultName":"Zeichenfläche {number}","artboard.add":"Zeichenfläche hinzufügen","artboard.delete":"Zeichenfläche löschen","layer.title":"Ebenen","layer.defaultName":"Ebene {number}","layer.add":"Ebene hinzufügen","layer.rename":"Ebene umbenennen","layer.reorder":"Ebenen neu anordnen","layer.delete":"Ebene löschen","layer.hide":"Ausblenden","layer.show":"Einblenden","layer.unlock":"Entsperren","layer.lock":"Sperren","layer.up":"Nach oben","layer.down":"Nach unten",
  "gradient.title":"Verlauf","gradient.apply":"Verlauf auf Füllung anwenden","gradient.linear":"Linear","gradient.radial":"Radial","gradient.stop":"+ Stopp","pattern.title":"Muster","pattern.dots":"Punkte","pattern.stripes":"Streifen","pattern.grid":"Raster","pattern.checkerboard":"Schachbrett","pattern.size":"Größe","pattern.colors":"Farbe / Hintergrund","filter.title":"Filter","filter.blur":"Weichzeichnen","filter.shadow":"Schlagschatten","filter.radius":"Radius","filter.offset":"Versatz X / Y","filter.colorOpacity":"Farbe / Deckkraft",
  "png.title":"Als PNG exportieren","png.width":"Breite (px)","png.height":"Höhe (px)","image.title":"Bild importieren","image.choose":"Datei auswählen…","image.raster":"Eingebettetes Bild","image.vector":"Vektor (Vektorisierung)","image.rasterHint":"Das Bild wird unverändert in das SVG eingebettet (Base64-kodiert).","image.quickSettings":"Schnelleinstellungen","image.presetLogo":"Farblogo","image.presetSilhouette":"Silhouette","image.presetDetailed":"Detaillierte Zeichnung","image.presetStencil":"Ausschnitt / Schablone","image.colorMode":"Farbmodus","image.color":"Farbe","image.blackWhite":"Schwarz-Weiß","image.traceStyle":"Vektorisierungsstil","image.curves":"Kurven","image.polygons":"Polygone","image.pixels":"Pixel (roh)","image.layers":"Ebenen","image.stacked":"Gestapelt","image.cutout":"Ausgeschnitten","image.colorPrecision":"Farbgenauigkeit","image.noise":"Rauschen filtern (px)","image.corner":"Winkelschwelle","image.advanced":"Erweiterte Optionen","image.layerDifference":"Ebenenunterschied","image.length":"Längenschwelle","image.iterations":"Max. Iterationen","image.splice":"Verbindungsschwelle","image.pathPrecision":"Pfadgenauigkeit (Dezimalstellen)","image.importing":"Importieren…",
  "document.defaultText":"Text","file.project":"Atelier-Vecteur-Projekt","file.image":"Bild","file.untitled":"unbenannt"
});

Object.assign(es, {
  "command.addArtboard":"Añadir mesa de trabajo","command.deleteArtboard":"Eliminar mesa de trabajo","command.editArtboard":"Modificar mesa de trabajo","command.addLayer":"Añadir capa","command.applyBlur":"Aplicar desenfoque","command.applyShadow":"Aplicar sombra paralela","command.removeFilter":"Quitar filtro","command.applyGradient":"Aplicar degradado","command.removeGradient":"Quitar degradado","command.applyPattern":"Aplicar patrón","command.removePattern":"Quitar patrón","command.changeFont":"Cambiar fuente","command.changeText":"Modificar texto","command.importImage":"Importar imagen","command.traceImage":"Vectorizar imagen","command.addElement":"Añadir elemento","command.addElements":"Añadir elementos","command.delete":"Eliminar","command.group":"Agrupar","command.ungroup":"Desagrupar","command.transform":"Transformar","command.resize":"Redimensionar","command.style":"Modificar estilo","command.path":"Modificar trazado","command.gradient":"Modificar degradado","command.pattern":"Modificar patrón","command.filter":"Modificar filtro","command.textToPath":"Convertir texto en trazado"
});
Object.assign(de, {
  "command.addArtboard":"Zeichenfläche hinzufügen","command.deleteArtboard":"Zeichenfläche löschen","command.editArtboard":"Zeichenfläche bearbeiten","command.addLayer":"Ebene hinzufügen","command.applyBlur":"Weichzeichnen anwenden","command.applyShadow":"Schlagschatten anwenden","command.removeFilter":"Filter entfernen","command.applyGradient":"Verlauf anwenden","command.removeGradient":"Verlauf entfernen","command.applyPattern":"Muster anwenden","command.removePattern":"Muster entfernen","command.changeFont":"Schrift ändern","command.changeText":"Text bearbeiten","command.importImage":"Bild importieren","command.traceImage":"Bild vektorisieren","command.addElement":"Element hinzufügen","command.addElements":"Elemente hinzufügen","command.delete":"Löschen","command.group":"Gruppieren","command.ungroup":"Gruppierung aufheben","command.transform":"Transformieren","command.resize":"Größe ändern","command.style":"Stil ändern","command.path":"Pfad bearbeiten","command.gradient":"Verlauf bearbeiten","command.pattern":"Muster bearbeiten","command.filter":"Filter bearbeiten","command.textToPath":"Text in Pfad umwandeln"
});

export const translations: Record<Language, Record<MessageKey, string>> = { fr: { ...fr }, en, es, de };

export function detectSystemLanguage(): Language {
  const candidates = typeof navigator === "undefined" ? [] : [...(navigator.languages ?? []), navigator.language];
  for (const candidate of candidates) {
    const code = candidate?.toLowerCase().split("-")[0] as Language;
    if (SUPPORTED_LANGUAGES.includes(code)) return code;
  }
  return "en";
}

let activeLanguage: Language = detectSystemLanguage();
export function setActiveLanguage(language: Language) { activeLanguage = language; }
export function getActiveLanguage() { return activeLanguage; }
export function t(key: MessageKey, params: TranslationParams = {}, language = activeLanguage): string {
  const template = translations[language][key] ?? translations.en[key] ?? translations.fr[key];
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`));
}

const BACKEND_ERRORS: Record<string, MessageKey> = {
  "image.unsupported": "error.imageUnsupported", "image.too_large": "error.imageTooLarge", "image.empty": "error.imageEmpty", "image.trace_too_complex": "error.traceTooComplex", "image.trace_failed": "error.traceFailed", "recovery.too_large": "error.recoveryTooLarge", "export.invalid_dimensions": "error.invalidDimensions", "export.extension": "error.destinationExtension", "text.no_contours": "error.textToPath",
};
export function localizedError(error: unknown, fallback: MessageKey): string {
  const raw = error instanceof Error ? error.message : typeof error === "string" ? error : "";
  if (raw.startsWith("i18n:")) {
    const [code, ...values] = raw.slice(5).split(":");
    const key = BACKEND_ERRORS[code];
    if (key) return t(key, { count: values[0] ?? "", limit: values[1] ?? "", extension: values[0] ?? "" });
  }
  // Keep errors that were already created from the active catalogue, but never
  // expose raw library/OS messages: those are not guaranteed to use the chosen UI language.
  if (raw.trim() && Object.values(translations[activeLanguage]).includes(raw)) return raw;
  return t(fallback);
}
